language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sakenda/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakenda/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-test"
  env: "Dockerreacttest-env"
  bucket_name: "elasticbeanstalk-us-east-2-490870217286"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY